export const CITIES_DATA = [
  { name: 'London', country: 'UK', slug: 'london' },
  { name: 'Manchester', country: 'UK', slug: 'manchester' },
  { name: 'Birmingham', country: 'UK', slug: 'birmingham' },
  { name: 'Edinburgh', country: 'UK', slug: 'edinburgh' },
];

export const BASELINES_DATA: Record<string, { ukvi: number; minimum: number }> = {
  london: { ukvi: 1483, minimum: 1282 },
  manchester: { ukvi: 1334, minimum: 950 },
  birmingham: { ukvi: 1334, minimum: 920 },
  edinburgh: { ukvi: 1334, minimum: 1000 },
};

export type PresetSeed = {
  band: 'low' | 'typical' | 'high';
  housing_type: string;
  rent_lower: number;
  rent_upper: number;
  people_sharing: number;
  deposit: number;
  bills_included: boolean;
  student_council_tax_exemption: boolean;
  electricity: number;
  gas: number;
  water: number;
  internet: number;
  budget_lower: number;
  budget_upper: number;
  groceries_weekly: number;
  meals_out_per_week: number;
  avg_meal_cost: number;
  coffees_per_week: number;
  avg_coffee_cost: number;
  transport_pass: number;
  phone: number;
  health_insurance: number;
  gym: number;
  subscriptions: number;
  clothing: number;
  personal_care: number;
  other_recurring: number;
  upfront_one_off: number;
  amortized_one_off: number;
  amortize_over_months: number;
  buffer: number;
};

export const PRESETS_DATA: Record<string, PresetSeed[]> = {
  london: [
    {
      band: 'low',
      housing_type: 'Shared room',
      rent_lower: 600,
      rent_upper: 800,
      people_sharing: 3,
      deposit: 700,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 40,
      gas: 30,
      water: 15,
      internet: 15,
      budget_lower: 600,
      budget_upper: 700,
      groceries_weekly: 35,
      meals_out_per_week: 1,
      avg_meal_cost: 10,
      coffees_per_week: 3,
      avg_coffee_cost: 3,
      transport_pass: 120,
      phone: 15,
      health_insurance: 0,
      gym: 0,
      subscriptions: 10,
      clothing: 20,
      personal_care: 15,
      other_recurring: 0,
      upfront_one_off: 500,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.05,
    },
    {
      band: 'typical',
      housing_type: 'Shared room',
      rent_lower: 900,
      rent_upper: 1050,
      people_sharing: 2,
      deposit: 975,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 48,
      gas: 36,
      water: 18,
      internet: 18,
      budget_lower: 600,
      budget_upper: 700,
      groceries_weekly: 43.85,
      meals_out_per_week: 2,
      avg_meal_cost: 12,
      coffees_per_week: 5,
      avg_coffee_cost: 3,
      transport_pass: 172,
      phone: 20,
      health_insurance: 0,
      gym: 25,
      subscriptions: 15,
      clothing: 35,
      personal_care: 25,
      other_recurring: 0,
      upfront_one_off: 500,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.1,
    },
    {
      band: 'high',
      housing_type: 'Studio',
      rent_lower: 1100,
      rent_upper: 1400,
      people_sharing: 1,
      deposit: 1250,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 60,
      gas: 45,
      water: 20,
      internet: 20,
      budget_lower: 1200,
      budget_upper: 1400,
      groceries_weekly: 60,
      meals_out_per_week: 4,
      avg_meal_cost: 18,
      coffees_per_week: 7,
      avg_coffee_cost: 4,
      transport_pass: 200,
      phone: 30,
      health_insurance: 30,
      gym: 50,
      subscriptions: 25,
      clothing: 60,
      personal_care: 40,
      other_recurring: 20,
      upfront_one_off: 800,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.1,
    },
  ],
  manchester: [
    {
      band: 'low',
      housing_type: 'Shared room',
      rent_lower: 400,
      rent_upper: 550,
      people_sharing: 3,
      deposit: 450,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 35,
      gas: 28,
      water: 15,
      internet: 15,
      budget_lower: 500,
      budget_upper: 650,
      groceries_weekly: 30,
      meals_out_per_week: 1,
      avg_meal_cost: 9,
      coffees_per_week: 2,
      avg_coffee_cost: 3,
      transport_pass: 65,
      phone: 15,
      health_insurance: 0,
      gym: 0,
      subscriptions: 10,
      clothing: 15,
      personal_care: 12,
      other_recurring: 0,
      upfront_one_off: 400,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.05,
    },
    {
      band: 'typical',
      housing_type: 'Shared room',
      rent_lower: 550,
      rent_upper: 750,
      people_sharing: 2,
      deposit: 650,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 42,
      gas: 32,
      water: 16,
      internet: 16,
      budget_lower: 700,
      budget_upper: 900,
      groceries_weekly: 38,
      meals_out_per_week: 2,
      avg_meal_cost: 11,
      coffees_per_week: 4,
      avg_coffee_cost: 3,
      transport_pass: 88,
      phone: 18,
      health_insurance: 0,
      gym: 20,
      subscriptions: 15,
      clothing: 25,
      personal_care: 20,
      other_recurring: 0,
      upfront_one_off: 450,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.1,
    },
    {
      band: 'high',
      housing_type: 'Studio',
      rent_lower: 750,
      rent_upper: 1000,
      people_sharing: 1,
      deposit: 875,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 55,
      gas: 40,
      water: 18,
      internet: 20,
      budget_lower: 1000,
      budget_upper: 1200,
      groceries_weekly: 55,
      meals_out_per_week: 3,
      avg_meal_cost: 15,
      coffees_per_week: 6,
      avg_coffee_cost: 3.5,
      transport_pass: 120,
      phone: 25,
      health_insurance: 20,
      gym: 40,
      subscriptions: 20,
      clothing: 50,
      personal_care: 30,
      other_recurring: 15,
      upfront_one_off: 600,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.1,
    },
  ],
  birmingham: [
    {
      band: 'low',
      housing_type: 'Shared room',
      rent_lower: 380,
      rent_upper: 520,
      people_sharing: 3,
      deposit: 420,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 34,
      gas: 27,
      water: 14,
      internet: 15,
      budget_lower: 450,
      budget_upper: 600,
      groceries_weekly: 28,
      meals_out_per_week: 1,
      avg_meal_cost: 9,
      coffees_per_week: 2,
      avg_coffee_cost: 2.8,
      transport_pass: 60,
      phone: 15,
      health_insurance: 0,
      gym: 0,
      subscriptions: 10,
      clothing: 15,
      personal_care: 12,
      other_recurring: 0,
      upfront_one_off: 350,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.05,
    },
    {
      band: 'typical',
      housing_type: 'Shared room',
      rent_lower: 520,
      rent_upper: 720,
      people_sharing: 2,
      deposit: 620,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 40,
      gas: 30,
      water: 15,
      internet: 16,
      budget_lower: 650,
      budget_upper: 850,
      groceries_weekly: 36,
      meals_out_per_week: 2,
      avg_meal_cost: 10,
      coffees_per_week: 3,
      avg_coffee_cost: 3,
      transport_pass: 80,
      phone: 18,
      health_insurance: 0,
      gym: 20,
      subscriptions: 12,
      clothing: 22,
      personal_care: 18,
      other_recurring: 0,
      upfront_one_off: 420,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.1,
    },
    {
      band: 'high',
      housing_type: 'Studio',
      rent_lower: 720,
      rent_upper: 950,
      people_sharing: 1,
      deposit: 835,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 52,
      gas: 38,
      water: 17,
      internet: 20,
      budget_lower: 950,
      budget_upper: 1150,
      groceries_weekly: 52,
      meals_out_per_week: 3,
      avg_meal_cost: 14,
      coffees_per_week: 5,
      avg_coffee_cost: 3.2,
      transport_pass: 110,
      phone: 25,
      health_insurance: 20,
      gym: 35,
      subscriptions: 18,
      clothing: 45,
      personal_care: 28,
      other_recurring: 10,
      upfront_one_off: 550,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.1,
    },
  ],
  edinburgh: [
    {
      band: 'low',
      housing_type: 'Shared room',
      rent_lower: 500,
      rent_upper: 650,
      people_sharing: 3,
      deposit: 575,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 38,
      gas: 30,
      water: 16,
      internet: 15,
      budget_lower: 550,
      budget_upper: 700,
      groceries_weekly: 33,
      meals_out_per_week: 1,
      avg_meal_cost: 10,
      coffees_per_week: 3,
      avg_coffee_cost: 3,
      transport_pass: 58,
      phone: 15,
      health_insurance: 0,
      gym: 0,
      subscriptions: 10,
      clothing: 18,
      personal_care: 14,
      other_recurring: 0,
      upfront_one_off: 450,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.05,
    },
    {
      band: 'typical',
      housing_type: 'Shared room',
      rent_lower: 650,
      rent_upper: 850,
      people_sharing: 2,
      deposit: 750,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 45,
      gas: 34,
      water: 17,
      internet: 17,
      budget_lower: 750,
      budget_upper: 950,
      groceries_weekly: 40,
      meals_out_per_week: 2,
      avg_meal_cost: 12,
      coffees_per_week: 4,
      avg_coffee_cost: 3.2,
      transport_pass: 75,
      phone: 18,
      health_insurance: 0,
      gym: 22,
      subscriptions: 14,
      clothing: 28,
      personal_care: 22,
      other_recurring: 0,
      upfront_one_off: 500,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.1,
    },
    {
      band: 'high',
      housing_type: 'Studio',
      rent_lower: 850,
      rent_upper: 1150,
      people_sharing: 1,
      deposit: 1000,
      bills_included: false,
      student_council_tax_exemption: true,
      electricity: 58,
      gas: 42,
      water: 19,
      internet: 20,
      budget_lower: 1050,
      budget_upper: 1250,
      groceries_weekly: 58,
      meals_out_per_week: 3,
      avg_meal_cost: 16,
      coffees_per_week: 6,
      avg_coffee_cost: 3.5,
      transport_pass: 100,
      phone: 28,
      health_insurance: 25,
      gym: 45,
      subscriptions: 22,
      clothing: 55,
      personal_care: 35,
      other_recurring: 15,
      upfront_one_off: 700,
      amortized_one_off: 0,
      amortize_over_months: 12,
      buffer: 0.1,
    },
  ],
};